site_name: OCR Layout Helper
nav:
    - Home: index.md
theme:
  name: 'material'
  palette:
    primary: 'blue'
  feature:
    tabs: true
extra_css:
  - 'extra.css'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
repo_url: https://puthurr.github.com/ocrlayout
edit_uri: blob/master/docs/